### ISSUE TITLE
Doesn't install on Ubuntu

### ISSUE THREAD

**Issue by bontchev** [posborne/dbus-python#3]
I need this, because `keyring` depends on it, but I am unable to install it on my Ubuntu machine. The command

``
sudo apt-get build-dep python-dbus
``

fails with the error message

```
Picking 'dbus-python' as source package instead of 'python-dbus'
E: Unable to find a source package for dbus-python
```

The command

```
sudo -H pip install -U git+https://github.com/posborne/dbus-python.git
```

also fails. Here is what it produces:

```
Collecting git+https://github.com/posborne/dbus-python.git
  Cloning https://github.com/posborne/dbus-python.git to /tmp/pip-NRc4in-build
Installing collected packages: dbus-python
  Running setup.py install for dbus-python ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-NRc4in-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bz7mvZ-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/dbus
    copying dbus/_expat_introspect_parser.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/server.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/service.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/exceptions.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/types.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/proxies.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/_dbus.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/glib.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/connection.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/lowlevel.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/bus.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/decorators.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/gi_service.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/__init__.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/_compat.py -> build/lib.linux-x86_64-2.7/dbus
    copying dbus/gobject_service.py -> build/lib.linux-x86_64-2.7/dbus
    creating build/lib.linux-x86_64-2.7/dbus/mainloop
    copying dbus/mainloop/glib.py -> build/lib.linux-x86_64-2.7/dbus/mainloop
    copying dbus/mainloop/__init__.py -> build/lib.linux-x86_64-2.7/dbus/mainloop
    running build_ext
    /tmp/pip-NRc4in-build/autogen.sh
    I am going to run ./configure with no arguments - if you wish
    to pass any to it, please specify them on the /tmp/pip-NRc4in-build/autogen.sh command line.
    Running autoreconf -f -i...
    configure.ac:52: error: possibly undefined macro: AC_DISABLE_STATIC
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.
    configure.ac:59: error: possibly undefined macro: AC_PROG_LIBTOOL
    autoreconf: /usr/bin/autoconf failed with exit status: 1
    configure: WARNING: unrecognized options: --enable-maintainer-mode
    configure: creating cache config.cache
    checking whether make supports nested variables... yes
    configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

    Now run 'make' to compile dbus-python.
    make -C /tmp/pip-NRc4in-build
    make: Entering directory `/tmp/pip-NRc4in-build'
    make: *** No targets specified and no makefile found.  Stop.
    make: Leaving directory `/tmp/pip-NRc4in-build'
    error: command 'make' failed with exit status 2

    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-NRc4in-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bz7mvZ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-NRc4in-build/
```

Any suggestions?

**Comment by deadalus-wings** [comment]
Hi I think I have the same problem
I tried installing using - sudo pip install dbus-python

> Collecting dbus-python
  Downloading https://files.pythonhosted.org/packages/3f/e7/4edb582d1ffd5ac3c84188deea32e960b5c8c0fe1da56ce70224f85ce542/dbus-python-1.2.8.tar.gz (787kB)
    100% |████████████████████████████████| 788kB 654kB/s 
Installing collected packages: dbus-python
  Running setup.py install for dbus-python ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-totur0uc/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-v3s9zljm/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    creating /tmp/pip-install-totur0uc/dbus-python/build
    creating /tmp/pip-install-totur0uc/dbus-python/build/temp.linux-x86_64-3.5
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking minix/config.h usability... no
    checking minix/config.h presence... no
    checking for minix/config.h... no
    checking whether it is safe to define __EXTENSIONS__... yes
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... no
    checking for mawk... mawk
    checking whether make sets $(MAKE)... yes
    checking for style of include used by make... GNU
    checking whether UID '0' is supported by ustar format... yes
    checking whether GID '0' is supported by ustar format... yes
    checking how to create a ustar tar archive... gnutar
    checking dependency style of gcc... gcc3
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking for native Windows host... no
    checking how to print strings... printf
    checking for a sed that does not truncate output... /bin/sed
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /bin/dd
    checking how to truncate binary pipes... /bin/dd bs=4096 count=1
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking for inline... inline
    checking for gawk... (cached) mawk
    checking for python... /usr/bin/python3
    checking for a version of Python >= '2.1.0'... yes
    checking for a version of Python >= '2.7'... yes
    checking for the distutils Python package... yes
    checking for Python include path... -I/usr/include/python3.5m
    checking for Python library path... -L/usr/lib -lpython3.5m
    checking for Python site-packages path... /usr/lib/python3/dist-packages
    checking python extra libraries... -lpthread -ldl  -lutil -lm
    checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
    checking consistency of all components of python development environment... no
    configure: error: in `/tmp/pip-install-totur0uc/dbus-python/build/temp.linux-x86_64-3.5':
    configure: error:
      Could not link test program to Python. Maybe the main Python library has been
      installed in some non-standard library path. If so, pass it to configure,
      via the LIBS environment variable.
      Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
      ============================================================================
       ERROR!
       You probably have to install the development version of the Python package
       for your distribution.  The exact name of this package varies among them.
      ============================================================================
    
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-totur0uc/dbus-python/setup.py", line 109, in <module>
        tests_require=['tap.py'],
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-totur0uc/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-install-totur0uc/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-install-totur0uc/dbus-python/build/temp.linux-x86_64-3.5/prefix']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-totur0uc/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-v3s9zljm/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-totur0uc/dbus-python/


Any solve for this?
