### ISSUE TITLE
pip install dbus-python failed

### ISSUE THREAD

**Issue by snowuyl** [posborne/dbus-python#6]
pip install dbus-python
Collecting dbus-python
  Downloading dbus-python-1.3.2.tar.gz (605 kB)
     ---------------------------------------- 605.5/605.5 kB 2.1 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      Collecting meson-python>=0.8.1
        Obtaining dependency information for meson-python>=0.8.1 from https://files.pythonhosted.org/packages/5e/ad/c51b346930e7050cae81bb9f360986da30e27e1bffd28a8495fcbe84ec73/meson_python-0.13.2-py3-none-any.whl.metadata
        Downloading meson_python-0.13.2-py3-none-any.whl.metadata (4.1 kB)
      Collecting meson>=0.60.0
        Obtaining dependency information for meson>=0.60.0 from https://files.pythonhosted.org/packages/ae/33/6f4a76e7139cffc2e3d4bab02824875c842922c0689438fc25092d85aecd/meson-1.2.0-py3-none-any.whl.metadata
        Downloading meson-1.2.0-py3-none-any.whl.metadata (1.7 kB)
      Collecting ninja
        Downloading ninja-1.11.1-py2.py3-none-win_amd64.whl (313 kB)
           -------------------------------------- 313.0/313.0 kB 1.2 MB/s eta 0:00:00
      Collecting patchelf
        Downloading patchelf-0.17.2.1.tar.gz (167 kB)
           -------------------------------------- 167.5/167.5 kB 2.5 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting setuptools
        Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/c7/42/be1c7bbdd83e1bfb160c94b9cafd8e25efc7400346cf7ccdbdb452c467fa/setuptools-68.0.0-py3-none-any.whl.metadata
        Using cached setuptools-68.0.0-py3-none-any.whl.metadata (6.4 kB)
      Collecting wheel
        Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
      Collecting colorama (from meson-python>=0.8.1)
        Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
      Collecting pyproject-metadata>=0.7.1 (from meson-python>=0.8.1)
        Downloading pyproject_metadata-0.7.1-py3-none-any.whl (7.4 kB)
      Collecting packaging>=19.0 (from pyproject-metadata>=0.7.1->meson-python>=0.8.1)
        Using cached packaging-23.1-py3-none-any.whl (48 kB)
      Downloading meson_python-0.13.2-py3-none-any.whl (79 kB)
         ---------------------------------------- 79.5/79.5 kB ? eta 0:00:00
      Downloading meson-1.2.0-py3-none-any.whl (962 kB)
         ---------------------------------------- 962.4/962.4 kB 7.6 MB/s eta 0:00:00
      Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
      Building wheels for collected packages: patchelf
        Building wheel for patchelf (pyproject.toml): started
        Building wheel for patchelf (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Building wheel for patchelf (pyproject.toml) did not run successfully.
        exit code: 1

        [11 lines of output]
        Traceback (most recent call last):
          File "C:\Users\amengine\AppData\Local\Temp\pip-build-env-1o8sosxw\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 645, in setup
            cmkr = cmaker.CMaker(cmake_executable)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\amengine\AppData\Local\Temp\pip-build-env-1o8sosxw\overlay\Lib\site-packages\skbuild\cmaker.py", line 148, in __init__
            self.cmake_version = get_cmake_version(self.cmake_executable)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\amengine\AppData\Local\Temp\pip-build-env-1o8sosxw\overlay\Lib\site-packages\skbuild\cmaker.py", line 105, in get_cmake_version
            raise SKBuildError(msg) from err

        Problem with the CMake installation, aborting build. CMake executable is cmake
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for patchelf
      Failed to build patchelf
      ERROR: Could not build wheels for patchelf, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

D:\AmHrvWin>

**Comment by 0xD8C4A475** [comment]
```
pip install -U git+https://github.com/posborne/dbus-python.git
```
